# -*- coding: utf-8 -*-
"""
Indices for the state variables
"""

# Returns idx, a dictionary containing the state variable names ('keys') and their corresponding index ('values')
def set_indices():
    
    idx = { 
            'E_t': 0,       # Proportion of excitatory cells firing per unit time [-]        
            'I_t': 1,       # Proportion of inhibitory cells firing per unit time [-]      
            'K_e': 2,       # Extracellular K+ concentration [mM]       
            'Na_sa': 3,     # Na+ concentration in the soma/axon [mM]       
            'Na_d': 4,      # Na+ concentration in the dendrite [mM]    
            'O2': 5,        # Tissue oxygen concentration [mM]        
            'CBV': 6,       # Nondimensional cerebral blood volume [-]    
            'HbR': 7,       # Normalised deoxyhemoglobin concentration [-]       
            'Ca_n': 8,      # Neuronal Ca2+ concentration [uM]       
            'nNOS': 9,     # Neuronal nitric oxide synthase concentration [uM]
            'NO_n': 10,     # Neuronal nitric oxide concentration [uM]         
            'v_k': 11,      # Astrocytic membrane potential [mV] 
            'K_p': 12,      # Perivascular K+ concentration [uM] 
            'Ca_p': 13,     # Perivascular Ca2+ concentration [uM] 
            'Na_k': 14,     # Astrocytic Na+ concentration [uM]
            'K_k': 15,      # Astrocytic K+ concentration [uM] 
            'Cl_k': 16,     # Astrocytic Cl- concentration [uM] 
            'HCO3_k': 17,   # Astrocytic HCO3- concentration [uM]
            'Na_s': 18,     # Synaptic Na+ concentration [uM] 
            'K_s': 19,      # Synaptic K+ concentration [uM] 
            'HCO3_s': 20,   # Synaptic HCO3- concentration [uM] 
            'w_k': 21,      # Open probability of the astrocytic BK channel [-] 
            'I_k': 22,      # Astrocytic IP3 concentration [uM]
            'Ca_k': 23,     # Astrocytic Ca2+ concentration [uM] 
            'h_k': 24,      # Inactivation variable of the astrocytic IP3R channel [-] 
            's_k': 25,      # Ca2+ concentration in the astrocytic ER [uM] 
            'm_k': 26,      # Open probability of the astrocytic TRPV4 channel [-] 
            'eet_k': 27,    # Astrocytic EET concentration [uM] 
            'NO_k': 28,     # Astrocytic nitric oxide concentration [uM] 
            'AA_k': 29,     # Astrocytic arachidonic acid concentration [uM]
            'Ca_i': 30,     # SMC Ca2+ concentration [uM]
            's_i': 31,      # Ca2+ concentration in the SR of the SMC [uM]
            'v_i': 32,      # SMC membrane potential [mV]
            'w_i': 33,      # Open probability of the SMC BK channel [-]
            'I_i': 34,      # SMC IP3 concentration [uM]
            'NO_i': 35,     # SMC nitric oxide concentration [uM] 
            'E_b': 36,      # Fraction of sGC in the basal state [-]
            'E_6c': 37,     # Fraction of sGC in the intermediate form [-] 
            'cGMP_i': 38,   # SMC cGMP concentration [uM]
            'H_i': 39,      # SMC 20-HETE concentration [uM]
            'AA_i': 40,     # SMC arachidonic acid concentration [uM]
            'Ca_j': 41,     # EC Ca2+ concentration [uM]
            's_j': 42,      # Ca2+ concentration in the ER of the EC [uM]
            'v_j': 43,      # EC membrane potential [mV]
            'I_j': 44,      # EC IP3 concentration [uM]
            'eNOS': 45,     # Endothelial nitric oxide synthase concentration [uM]
            'NO_j': 46,     # EC nitric oxide concentration [uM] 
            'Mp': 47,       # Fraction of free phosphorylated cross-bridges [-]
            'AMp': 48,      # Fraction of attached phosphorylated cross-bridges [-]
            'AM': 49,       # Fraction of attached dephosphorylated cross-bridges [-]
            'R': 50}#,         # Arteriolar radius [um]
#            'GABA': 51,     # Normalised GABA concentration [-]
#            'Glu': 52,      # Normalised glutamate concentration [-]
#            'NPY': 53}      # Normalised NPY concentration [-]

    return idx